"""A real, streaming multi-agent debate.

The Care Coordinator convenes the engaged specialists; each gives an opening
statement, they cross-examine each other (curated rebuttals where domains
genuinely tension — e.g. Sleep vs Nutrition on late meals), the Safety Reviewer
weighs in, and Synthesis delivers the verdict. Emitted as a token stream so the
UI can render the debate unfolding turn by turn.

Two modes:
- Grounded (default, runs offline): turns are the agents' grounded contributions,
  streamed word-by-word.
- Live (ANTHROPIC_API_KEY set): each turn is generated by a real model given that
  agent's persona + the user's derived facts + the transcript so far. Only derived
  summaries are sent — never raw PHI.
"""

from __future__ import annotations

import asyncio
import os
from typing import AsyncIterator

from ..config import agent_live
from .context import coupling_line
from .orchestrator import BY_KEY, COORD, GREET, SAFETY, SPECIALISTS, STATUS, SYNTH, _overview

MODEL = os.getenv("COACH_MODEL", "claude-opus-4-8")

# Curated cross-examination — where two domains genuinely pull in different directions.
REBUTTALS: dict[tuple[str, str], str] = {
    ("sleep", "nutrition"): "within ~3 hours of bed even a good meal taxes your overnight coupling — I'd eat earlier, or keep the late one lighter.",
    ("nutrition", "sleep"): "fair — but pairing a late meal with a 10–15 min walk recovers most of the glucose cost, so it isn't all-or-nothing.",
    ("movement", "sleep"): "if we add an evening session, keep it ≥2 hours before bed so it doesn't lift your overnight heart rate.",
    ("sleep", "movement"): "agreed on training hard — just not late; your autonomic system needs the wind-down.",
    ("nutrition", "movement"): "and a short walk after the carb-heavier meal blunts the spike — cheap and effective.",
    ("labs", "nutrition"): "from the labs, your HbA1c is creeping, so steadier post-meal glucose is the metric that matters most here.",
    ("experiments", "sleep"): "we don't have to argue it — a 2-week bedtime crossover will show whether the coupling actually moves.",
    ("biosignals", "sleep"): "the wearables back you up — overnight is exactly where the drift shows.",
}


def _card(a) -> dict:
    return a.card()


async def _emit_words(text: str) -> AsyncIterator[dict]:
    for word in text.split():
        await asyncio.sleep(0.012)
        yield {"kind": "token", "text": word + " "}


def _facts_blurb(ctx: dict) -> str:
    watch = ", ".join(ctx.get("watch", [])) or "none"
    return (
        f"Name: {ctx.get('name')}. Biological age {ctx.get('bio_age')} vs {ctx.get('chron_age')} "
        f"(accel {ctx.get('age_accel')}), Δ {ctx.get('delta')} vs baseline. Systems on watch: {watch}. "
        f"Signal: {coupling_line(ctx)}."
    )


async def _emit_live(agent, ctx: dict, query: str, transcript: str) -> AsyncIterator[dict]:
    """Stream one agent's turn from a real model. Only derived facts are sent."""
    import anthropic  # lazy — only when a key is present

    client = anthropic.AsyncAnthropic()
    system = (
        f"You are the {agent.name} agent ({agent.title}) on a personalized longevity coaching "
        f"team. Speak in the first person in 1–2 sentences, grounded in the user's data below. Be "
        f"specific and wellness-scoped; defer medication/dosing/diagnosis to a clinician.\n\n"
        f"User's derived data: {_facts_blurb(ctx)}"
    )
    messages = [
        {
            "role": "user",
            "content": f"Question: {query}\n\nDebate so far:\n{transcript or '(you open)'}\n\nGive your take.",
        }
    ]
    async with client.messages.stream(model=MODEL, max_tokens=300, system=system, messages=messages) as stream:
        async for text in stream.text_stream:
            yield {"kind": "token", "text": text}


async def stream_debate(ctx: dict, query: str) -> AsyncIterator[dict]:
    q = (query or "").lower().strip()
    live = agent_live()
    scored = sorted(((s, s.relevance(q, ctx)) for s in SPECIALISTS), key=lambda x: -x[1])
    lead = ""

    if not q or q in GREET:
        lead = _overview(ctx)
        engaged = [BY_KEY["signals"], BY_KEY["sleep"]]
    elif any(k in q for k in STATUS):
        lead = _overview(ctx)
        engaged = [BY_KEY["signals"], BY_KEY["sleep"], BY_KEY["labs"]]
    else:
        engaged = [s for s, r in scored if r >= 0.5][:3]
        if len(engaged) < 2:
            engaged = [scored[0][0], scored[1][0]]

    transcript = ""

    async def speak(agent, phase, text, citations=None):
        nonlocal transcript
        yield {"kind": "turn", "phase": phase, "agent": _card(agent)}
        spoken = ""
        if live and phase in ("opening", "rebuttal", "verdict"):
            async for ev in _emit_live(agent, ctx, query, transcript):
                spoken += ev["text"]
                yield ev
        else:
            spoken = text
            async for ev in _emit_words(text):
                yield ev
        transcript += f"{agent.name}: {spoken.strip()}\n"
        yield {"kind": "end_turn", "citations": citations or []}

    # 1) Coordinator frames the debate
    names = ", ".join(s.name for s in engaged)
    async for ev in speak(COORD, "frame", f"Let me convene the team on “{query}”. I'll hear from {names}, then reconcile."):
        yield ev

    # 2) Opening statements
    notes = []
    for s in engaged:
        n = s.contribute(q, ctx)
        if not n:
            continue
        notes.append(n)
        async for ev in speak(s, "opening", n.text, n.citations):
            yield ev

    # 3) Cross-examination — curated rebuttals where domains tension
    rebuttals = 0
    for s in engaged:
        for target in engaged:
            if target is s or rebuttals >= 3:
                continue
            t = REBUTTALS.get((s.key, target.key))
            if t:
                rebuttals += 1
                async for ev in speak(s, "rebuttal", f"To {target.name} — {t}"):
                    yield ev

    # 4) Safety review
    safety = SAFETY.review(q, notes, ctx)
    async for ev in speak(SAFETY, "safety", safety["note"]):
        yield ev

    # 5) Verdict
    reply = SYNTH.synthesize(q, ctx, notes, safety, lead)
    citations: list[str] = []
    for n in notes:
        for c in n.citations:
            if c not in citations:
                citations.append(c)
    async for ev in speak(SYNTH, "verdict", reply, citations):
        yield ev

    yield {"kind": "done", "citations": citations, "safety": safety, "reply": reply}
